name: CI - Feature Branch Build & Test

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Node/TS App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use your project's version

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Run unit tests with coverage
        run: npx vitest run --coverage

      - name: Bundle coverage report
        run: |
          mkdir -p coverage/html
          cp -r coverage/* coverage/html/
      - name: Upload coverage artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: test-coverage-report
          path: coverage/html
