name: Update Staging Environment Config on Pre-Release

on:
  release:
    types: [prereleased]

env:
  CONFIG_REPO_PAT: ${{ secrets.PAT_TOKEN }}
  CONFIG_REPO: CI_CD_Config_Repo
  TARGET_ENV: staging

jobs:
  helm-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v3

      - name: Clone config repo
        run: |
          git clone https://x-access-token:${CONFIG_REPO_PAT}@github.com/AlanJMac/${CONFIG_REPO}.git

      - name: Update staging Helm chart in config repo
        run: |
          rm -rf ${CONFIG_REPO}/charts/${TARGET_ENV}/
          mkdir -p ${CONFIG_REPO}/charts/${TARGET_ENV}
          cp -R ci-cd-example/ ${CONFIG_REPO}/charts/${TARGET_ENV}/

      - name: Commit and push changes to config repo
        run: |
          cd ${CONFIG_REPO}
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/${TARGET_ENV}/
          git commit -m "Update ${TARGET_ENV} Helm chart from build repo - $GITHUB_SHA"
          git push origin main

      - name: Create and push Git tag in config repo
        run: |
          cd ${CONFIG_REPO}
          git checkout main
          TAG="deploy-${GITHUB_REF_NAME}-${GITHUB_SHA::8}"
          git tag $TAG
          git push origin $TAG
