name: Update Staging Environment Config on Prerelease

on:
  release:
    types: [published]

jobs:
  helm-package:
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v3

      - name: Clone config repo
        env:
          CONFIG_REPO_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://x-access-token:${CONFIG_REPO_PAT}@github.com/AlanJMac/CI_CD_Config_Repo.git

      - name: Update staging Helm chart in config repo
        run: |
          rm -rf CI_CD_Config_Repo/charts/staging/
          mkdir -p CI_CD_Config_Repo/charts/staging
          cp -R ci-cd-example/ CI_CD_Config_Repo/charts/staging/

      - name: Commit and push changes to config repo
        env:
          CONFIG_REPO_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          cd CI_CD_Config_Repo
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/staging/
          git commit -m "Update staging Helm chart from build repo - $GITHUB_SHA"
          git push origin main

      - name: Create and push Git tag in config repo
        env:
          CONFIG_REPO_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          cd CI_CD_Config_Repo
          git checkout main
          TAG="deploy-${GITHUB_REF_NAME}-${GITHUB_SHA::8}"
          git tag $TAG
          git push origin $TAG
